{% set name = "lap" %}
{% set version = "0.4.0" %}
{% set sha256 = "c4dad9976f0e9f276d8a676a6d03632c3cb7ab7c80142e3b27303d49f0ed0e3b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - numpy 1.10.*,>=1.10.1  # [not (win and py36)]
    - numpy 1.11.*           # [win and py36]
  run:
    - python
    - numpy >=1.10.1  # [not (win and py36)]
    - numpy >=1.11    # [win and py36]

test:
  imports:
    - lap

about:
  home: https://github.com/gatagat/lap
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Linear Assignment Problem solver (LAPJV/LAPMOD).'
  dev_url: https://github.com/gatagat/lap

extra:
  recipe-maintainers:
    - primozgodec
