travis:
  secure:
    BINSTAR_TOKEN: Q9xh4ZcJbuAUhqv/MUMKgcy1p1GD+xn/r8UzOLodVB5Rs4gAAt3l4gocCZe+ZIi6TcJJdrWiJqzkeA1KLJdNZPz6ctpqIo731L4rcRQZTnPrWtxV2Rj8avnXNEuCUcf3xwuQdEPgwRbL1JcV5+kpHLmXh5/+9nYtsCASLV0F0V6uofpWSFkmM5znTMarfGngXgh+7dZZmPkiOqJ5phqIXwhXir0gpOfBODt6Eg4Jr1Hg6X2MMkVKqoASFCIn3xC4hJokyZVLV4PXcZbHHgrZ4578QGxr4Tf3X2PRbsKKym3PqMZa/zbn3gR9Ze3sPQ17kyYyKmQ69ZHVFRZhh4uGdDZNM7N5TeP/zlHQmHkMkprQZpzA+/B7eLfrs+HMYyAbNsN7TidcDJ+EpyVl/BoMZUUcF4NhGLPhFZb0C6PxB8BS+jDNbRfBHNQXTR6ZPIkYE3MDX90ILB+MMvKurgyThJBNCNQFDiBtg0iqhdCT8SzvlTUPnjZABu8BMO7VKVpyv4fjfrHbx+fzk1dfCVwwk6GX/Ydqitlz+t7YK0ECdBrHlU5E/UQl3/anLdJPipEUxzU7Bfgy/LmPsXtpZ3RzMaq8R7y5lmXM80knwDlQkIsJGqA795F1sgWjE2OAj4fwC38GDb7H5EC9yrT++EdlbhHN7Fk4tbP+zcF8X2b01nw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
