travis:
  secure:
    BINSTAR_TOKEN: L1XYa0uQOaq5j52CB7G67+N76whFeK+5PF+g4pLXaUjTV4lVIY9sYu98xqqqdp2nwp0mehsH8gK7FZ3/2+PAhIWInIhX3ShvypgEJ9+K9u3RTH/4GpmxxfAzLGzc9YZk2LsIgc4gsx84kPhhtsp7BAGtMX0dTSSnBrgAm7aslNCcz8l9nxmluwCYhj8KD1Bx+kCQy9S4svgVUmVi0TMipb7IHNLGW1TjT7I0MmsA0iCozeScyR71blCtrzF39aEznGty24vtol6OZo/V3hNgnHl8HRHfWOSimywpUu4uV/bHdKwO9sdAszBoO8T1bFHblQDHMGT38h+hwOZ7K2lDiA0kQWS97RRSkpbl804weGDnn9Ro6biJfAUHWl5/j850dWF7g+PrXpAaGe+BrFosBAmKQWg6t8cG2bkptx1ResFAiPMbPSic/sUSujDBa12/NkT3G9sENwDXJ3290NB7if7zWMWDuZzv7pVCQK4OIy6U4/Sho3MzOGzFOTKYkDRBq/JLT2AOFUWrC3KP/ADSOjsTl5OVPk3D/cqHuoGDEOfwjWwV+rBikggKZoyM45sVSY4rOfUBO/O2CcrIuX+Iqmof4RMO4Q/5zvg55bGAw3KXai+dUG83LhsZakoZDTJvVscSlYnTPTUIt9lnki9KD/RiJXq/VX8kmT3Mv2c+7EU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
